import { Participant } from '@/types';

export const MOCK_PARTICIPANTS: Participant[] = [
  {
    id: 'local',
    name: 'You',
    avatarColor: 'from-violet-500 to-purple-700',
    isMuted: false,
    isVideoOff: false,
    handRaised: false,
    mood: null,
    tensionInput: 30,
    isFacilitator: true,
  },
  {
    id: 'p2',
    name: 'Luna M.',
    avatarColor: 'from-emerald-500 to-teal-700',
    isMuted: false,
    isVideoOff: false,
    handRaised: false,
    mood: '😊',
    tensionInput: 45,
  },
  {
    id: 'p3',
    name: 'Sara K.',
    avatarColor: 'from-rose-500 to-pink-700',
    isMuted: true,
    isVideoOff: false,
    handRaised: false,
    mood: '😌',
    tensionInput: 20,
  },
  {
    id: 'p4',
    name: 'River T.',
    avatarColor: 'from-amber-500 to-orange-700',
    isMuted: false,
    isVideoOff: false,
    handRaised: true,
    mood: '😤',
    tensionInput: 70,
  },
  {
    id: 'p5',
    name: 'Jade L.',
    avatarColor: 'from-sky-500 to-blue-700',
    isMuted: false,
    isVideoOff: true,
    handRaised: false,
    mood: '🤩',
    tensionInput: 15,
  },
  {
    id: 'p6',
    name: 'Aria N.',
    avatarColor: 'from-lime-500 to-green-700',
    isMuted: false,
    isVideoOff: false,
    handRaised: false,
    mood: '😰',
    tensionInput: 60,
  },
  {
    id: 'p7',
    name: 'Kai B.',
    avatarColor: 'from-fuchsia-500 to-purple-700',
    isMuted: true,
    isVideoOff: false,
    handRaised: false,
    mood: '😔',
    tensionInput: 35,
  },
  {
    id: 'p8',
    name: 'Nova W.',
    avatarColor: 'from-cyan-500 to-teal-700',
    isMuted: false,
    isVideoOff: false,
    handRaised: false,
    mood: null,
    tensionInput: 50,
  },
];
